### ISSUE TITLE
blogDelete（ブログの削除ロジックを実行）の実装

### ISSUE THREAD

**Issue by kdnakt** [write-blog-every-week/reminder#9]
https://github.com/write-blog-every-week/write-blog-every-week-remind/blob/master/main.go#L104

**Comment by kojirock5260** [comment]
コレ実際使われてなさ気な感じがして、実装しなくてもいい気がしています。。。

**Comment by kdnakt** [comment]
クローズしちゃいます？

**Comment by kojirock5260** [comment]
そうですね！クローズしちゃいます！
